version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local