name: vercel
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '55 2 * * *' # 毎日10時00分（UTC）に実行
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.VERCEL_TOKEN }}
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC}}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
